name: Your action
description: Description for action
inputs:
  variable:
    default: "default value"
    type: string
    required: true
outputs:
  result:
    description: lol
runs:
  main: 'main.py'
  using: 'js'
