openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
x-yc-apigateway:
  service_account: <id> # Параметр верхнего уровня
paths:
  /:
    get:
      summary: Say hello
      operationId: hello
      parameters:
      - name: user
        in: query
        description: User name to appear in greetings
        required: false
        schema:
          type: string
          default: 'world'
      responses:
        '200':
          description: Greeting
          content:
            'text/plain':
               schema:
                 type: "string"
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Content-Type': text/plain
        content:
          'text/plain': Hello, World!

  /static/{file}: # Чтобы файлы были доступны на любом уровне вложенности /static/js/ и /static/CSS/ например, необходимо добавить + {file+}
    get:
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        bucket: scam
        object: '{file}'
        type: object_storage
        error_object: error.html
        presigned_redirect: true # Для запроса будет сгенерирован специальный тип URL, который содержит все данные для авторизации, он позволит любому пользователю скачать объект
        service_account: jkfk23afq4o3pv # Если не задан, то будет использованно значение параметра верхнего уровня
                                        # если так-же нет, то запрос будет происходить без авторизации (тогда нужен pub бакет)

  /example/{ID}: # Этот пример направит все запросы вне зависимости от метода на одну функцию
    x-yc-apigateway-any-method:
      summary: Operating with examples
      operationId: example
      tags:
        - example
      parameters:
        - name: ID
          in: path
          description: Return ID
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: b095c95icnvbuf4v755l
        tag: "$latest"
        service_account_id: <id>
