name: Your action
description: Description for action
inputs:
  variable:
    default: "default value"
    type: string
    required: true
outputs:
  result:
    description: lol
runs:
  using: 'composite'
  steps:
    - name: first step
      run: 
      shell: bash
