# Если репозиторий public, то можем запустить workflow так: fortnite-demon/repo/.github/actions/directory@main
# Также и с private или мы можем сделать checkout и указать путь

name: Your action
description: Description for action
inputs:
  variable:
    default: "default value"
    type: string
    required: true
outputs:
  result:
    description: lol
    value: ${{ steps.step1.outputs.versionOut }}
runs:
  using: 'composite'
  steps:
    - name: first step
      id: step1
      run: |
        echo "versionOut=v1.0.0" >> $GITHUB_OUTPUT
      shell: bash
