version: '3.8'
x-environment-defaults: &environment-defaults
  DB_NAME: "prediction"
  DB_USER: "prediction"
  DB_PASSWORD: "prediction"
  DB_PORT: 5432

services:
  service-name:
    ---------- Образ или путь к Dockerfile
    build:
      context: ./path
    или
    image: image:tag
    ----------
    
    sercrets:
      - mysercret
    env_file: ./.env
    ports:
      - "3000:3000"
    networks:
      - prediction-network
    volumes:
      - ./prediction:/app
      - static_volume:/app/static
    depends_on:
      postgres-db:
        condition: [ service_unhealthly, service_healthly (при наличии параметра healtcheck) ], started, service_completed, service_running 
        
    ---------- Переменные окружения
    environment:
      <<: *environment-defaults
    или
    environment:
      VAR: value
    ----------
    
    restart: on-failure:5 (пять попыток перезапуска), unless-stopped, always, no
    
    ---------- Проверяет контейнер на здоровье
    healthcheck:
      test: [ "CMD", "curl -f http://localhost:8000/api/health || exit 1" ]
      interval: 10s Через сколько
      timeout: 10s Сколько ждёт ответа
      retries: 3 Попытки
      start_period: 10s Через сколько после запуска контейнера
    ----------
    
    command: Команда при запуске
    entrypoint: ...

volumes:
  pg_data:
  static_volume:
  
secrets:
  mysecret:
    file: prediction-app/file.txt

networks:
  prediction-network:
    driver: bridge
