version: '3.8'
x-environment-defaults: &environment-defaults
  DEBUG: "False"
  DB_NAME: "prediction"
  DB_USER: "prediction"
  DB_PASSWORD: "prediction"
  DB_HOST: "postgres-db"
  DB_PORT: 5432
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  SECRET_KEY: "secret"

services:
  service-name:
    ----------
    build:
      context: ./path
    sercrets:
      - mysercret
    env_file: ./.env
    ports:
      - "3000:3000"
    networks:
      - prediction-network
    volumes:
      - ./prediction:/app
      - static_volume:/app/static
    depends_on:
      postgres-db:
        condition: service_unhealthly, service_healthly (при наличии параметра healtcheck), started, service_completed, service_running 
    environment:
      <<: *environment-defaults
    restart: on-failure:5
    healthcheck:
      test: [ "CMD", "curl -f http://localhost:8000/api/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  pg_data:
  static_volume:
  
secrets:
  mysecret:
    file: prediction-app/file.txt

networks:
  prediction-network:
    driver: bridge
