deploy:

  placement:
    constraints: [node.role == manager] или по label [node.labels.label == label]
    
  replicas: n

  resources:
    cpus:
    memory:
  reservation:
    cpus:
    memory:

  
docker node --availability=(drain, очистить и неактивное состояние) (active) <name>
