deploy:

  placement:
    constraints: [node.role == manager] или по label [node.labels.label == label]
    
  replicas: n

  resources:
    cpus:
    memory:
  reservation:
    cpus:
    memory:
  __________ Когда делаем обновление docker service update
  update_config:
    parallelism: 2
    delay: 1h1m10s

  
docker node --availability=(drain, очистить и неактивное состояние) (active) <name>
