deploy:

  placement:
    constraints: [node.role == manager] или по label [node.labels.label == label]
    
  replicas: n

  
docker node --availability=(drain, очистить и неактивное состояние) (active) <name>
