global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "pushgateway"
    metrics_path: /metrics
    honor_labels: true # Запрещает prometheus изменять поступающие лейблы job и instance своими собственными
    static_configs:
      - targets: ["localhost:9091"]
