---
- hosts: web:db                 # Хосты из web и db
         test:&db               # Хосты db в test 
         test:!db               # Исключает хосты db из test
         *.example.com          # Подстановка
         a[0-1].ex.com          # Диапазон
         ~a\d\.mearme\.(com|ru) # Регулярное выражение

         dev:test:&db:!queue    # Комбинированное выржание, результаты применяются слева на право
