---
- hosts: web:db                 # Хосты из web и db
         test:&db               # Хосты db в test 
         test:!db               # Исключает хосты db из test
         *.example.com          # Подстановка
         a[0-1].ex.com          # Диапазон
         ~a\d\.mearme\.(com|ru) # Регулярное выражение

         dev:test:&db:!queue    # Комбинированное выржание, результаты применяются слева на право
  serial: 1 или 50% # Сколько хостов нужно обрабатывать одновременно, можно также указать процент
    - 1             # можно указать также списком, например, есть 10 хостов, сначала будет обработан 1 хост,
    - 50%           # затем 5, а потом 4
  max_fail_percentage: 0 # Процент ошибок, при достижении которого сценарий завершится неудачей
