name: Matrix Workflow

on:
  push:

jobs:
  matrix-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        params:
          - version: v1.0.0
            env: # К последующим тоже будет применяться массив, например если будет вложенность у M1
              - M1: 1
                M2: 2
          - version: v2.0.0
            env:
              - M1: 1
                M2: 2
        exclude:
          - os: macos-latest
            params: { version: v2.0.0, env: [ {M1: 1, M2: 2} ] } 
            
    steps:
      - name: first step
        run: |
          echo Runs on ${{ matrix.os }} with ${{ matrix.params.env[0].M1 }}
